### ISSUE TITLE
Missing comparison of a closely related work

### ISSUE THREAD

**Issue by LFhase** [JinYujie99/WBM#1]
Hi,

Congratulations on your wonderful ICML work and thanks for your open-sourcing the code. When I read your paper, however, we found you missed discussion and comparison with a closely related work [CIGA](https://github.com/LFhase/CIGA) that achieves state-of-the-art graph size generalization performance on the **same datasets** and was published at NeurIPS2022. Although we understand there are distinctions in the focus of the two works, could you kindly make up the discussion of our work?

Best regards,
Yongqiang Chen

**Comment by JinYujie99** [comment]
We are sorry that we were not aware of this paper when we submitted our paper. Unfortunately, it has already passed the camera-ready deadline. We will make up the discussion of your work in the arXiv version later. We also hope you can understand that our main focus was on examining graph size generalization from the perspective of convergence rate, so we didn't compare it with all general graph OOD methods.

**Comment by LFhase** [comment]
Hi thanks for the clarification and planning to make up the discussion in arxiv version. It's understandable that one could miss some related works at the early stage of such an emerging field : )
